### ISSUE TITLE
Crawler failures

### ISSUE THREAD

**Issue by kesara** [ietf-tools/relaton-data-ieee#26]
There's been multiple failures in last few days[^1].
The crawler is failing while processing data:
```
File: ieee-rawbib/updates.20230831/IEEEUpdates_IEEEstd/week27b/4130.zip
undefined method `text' for nil:NilClass
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:160:in `block (2 levels) in parse_contributor'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:155:in `each_with_object'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:155:in `block in parse_contributor'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:153:in `map'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:153:in `parse_contributor'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:43:in `block in parse'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:43:in `each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_parser.rb:43:in `parse'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_fetcher.rb:102:in `fetch_doc'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_fetcher.rb:62:in `block in fetch'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_fetcher.rb:57:in `each'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_fetcher.rb:57:in `fetch'
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.14.8/lib/relaton_ieee/data_fetcher.rb:47:in `fetch'
crawler.rb:13:in `<main>'
```

[^1]: https://github.com/ietf-tools/relaton-data-ieee/actions/workflows/crawler.yml

**Comment by ronaldtse** [comment]
@kesara we are unable to track the failure as we do not have access to the rawbib repository. We could fix that with access.

**Comment by kesara** [comment]
@ronaldtse I've sent you a GitHub invitation to join a team that has access to the rawbib repository. Let me know if I should invite anyone else. Thanks.

**Comment by ronaldtse** [comment]
@kesara could you please help add @andrew2net @strogonoff @kwkwan @opoudjis ? Thanks!

**Comment by kesara** [comment]
@ronaldtse Done! I've sent invites.

**Comment by ronaldtse** [comment]
@kesara we are addressing this issue, will update.
